### ISSUE TITLE
Padding issue in mobile on page Statistics heroes winrates

### ISSUE THREAD

**Issue by anneback** [w3champions/website#422]
## Case
Hi I noticed that this [page](https://www.w3champions.com/OverallStatistics/heroes-winrates) doesn't look so good on mobile screen size.

https://www.w3champions.com/OverallStatistics/heroes-winrates

### Case Image
![W3Champions_rating](https://user-images.githubusercontent.com/2612174/130318655-ebb783d0-9823-4809-91d3-c6d5ec2a3680.jpeg)

## Solution
A suggestion would be to add a media query to it to set `padding: 0`:
```css
@media screen and (max-width: 480px) {
  .v-card__subtitle, .v-card__text, .v-card__title {
     padding: 0
  }
}
```

### Solution Output
<img width="406" alt="Screenshot 2021-08-21 at 12 08 04" src="https://user-images.githubusercontent.com/2612174/130318627-8f243074-fa4d-489c-b32c-51e08ac59a7e.png">
